language: ruby

before_script:
  - "RAILS_ENV=test bundle exec rake db:setup"

# See https://docs.travis-ci.com/user/languages/ruby/#bundler-20
before_install:
  - gem update --system
  - gem install bundler

# Faster builds (with less problems) https://docs.travis-ci.com/user/languages/ruby/#caching-bundler
bundler_args: --without production


notifications:
  slack: zeuswpi:Hn76dHiOHpvPHJVSlt93Dck0
  email:
    recipients:
      - gandalf@zeus.ugent.be
    on_success: never
    on_failure: change
