language: ruby

before_script:
  - "RAILS_ENV=test bundle exec rake db:setup"

notifications:
  slack: zeuswpi:Hn76dHiOHpvPHJVSlt93Dck0
  email:
    recipients:
      - gandalf@zeus.ugent.be
    on_success: never
    on_failure: change
