version: '3.3'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: saruman
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - saruman_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  db-test:
    image: postgres:16
    environment:
      POSTGRES_DB: saruman-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - saruman_test_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  saruman_data:
  saruman_test_data:
