version: '3'
services:
  mysql:
    image: mariadb:10
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: saruman
      MYSQL_USER: saruman
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
  saruman:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./public/system:/app/public/system
    ports:
      - 3000:3000
    environment:
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_LOG_TO_STDOUT: "true"
      DATABASE_URL: mysql2://saruman:password@mysql/saruman
    depends_on:
      - mysql
    links:
      - mysql:mysql
